project:
  type: website
  output-dir: docs

website:
  title: "miroo1974.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: assignments/index.qmd
        text: Assignments
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual